### ISSUE TITLE
Not accepting connections

### ISSUE THREAD

**Issue by HeisenbergK** [eminfedar/async-sockets-cpp#14]
Hello again,

for some reason, while running the example tcp server I cannot connect to the server.

It reaches the exit loop without errors, but while trying to connect I get errors that the server isn't available.

**Comment by HeisenbergK** [comment]
Found the error

`cout << newClient->remoteAddress() << endl;`

produces Segmentation Fault

**Comment by HeisenbergK** [comment]
Dag a little deeper.

`cout << newClient->remoteAddress() << endl;`
works if `newClient->onMessageReceived = [newClient](string message)`
but not if `newClient->onMessageReceived = [&](string message)`

Still, I want to use some variables (an ofstream) in the `onMessageReceived ` and I can't, without the `&` in the lambda.

**Comment by eminfedar** [comment]
The library is not thread-safe so you should write thread safe protections to prevent segment faults.

For example you can add mutexes when accessing same variable from different threads at the same time.

**Comment by TheBeardedQuack** [comment]
Urm, just a quick though... "async" is kinda about making threads easier to use.

Anyway I don't think this issue is part of the library, if you're calling an async function with a reference you must ensure that reference still exists when the callback will be called. This is down to the caller to sort out.

In that first snippet the variable is passed by value, so a copy is made. This means your data is available as expected in the callback handler because it was copied, it's not referencing data that no longer exists.
